Repository databute/databutee, pull requests merged in 2019-07, with the labels that each got.

#1 gitignore 업데이트
  .gitignore
Labels: enhancement

#2 README 업데이트
  README.md
Labels: enhancement

#3 Gradle 프로젝트 생성
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement

#4 메인 클래스 생성
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/DatabuteeConfiguration.java
Labels: enhancement

#5 기본적인 콘솔 입력 구현
  build.gradle
  src/main/java/databute/databutee/DatabuteeConstants.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/console/ConsoleConstants.java
Labels: enhancement

#6 서버와 통신 구현
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/DatabuteeConfiguration.java
  src/main/java/databute/databutee/DatabuteeConstants.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSession.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/Message.java
  src/main/java/databute/databutee/network/message/MessageCode.java
  src/main/java/databute/databutee/network/message/MessageCodeResolver.java
  src/main/java/databute/databutee/network/message/MessageDeserializer.java
  src/main/java/databute/databutee/network/message/MessageHandler.java
  src/main/java/databute/databutee/network/message/MessageSerializer.java
  src/main/java/databute/databutee/network/message/codec/MessageToPacketEncoder.java
  src/main/java/databute/databutee/network/message/codec/PacketToMessageDecoder.java
  src/main/java/databute/databutee/network/packet/AbstractPacket.java
  src/main/java/databute/databutee/network/packet/BufferedPacket.java
  src/main/java/databute/databutee/network/packet/Packet.java
  src/main/java/databute/databutee/network/packet/codec/ByteToPacketDecoder.java
  src/main/java/databute/databutee/network/packet/codec/PacketToByteEncoder.java
Labels: enhancement

#11 설정된 서버 주소들 중 한 주소만 임의로 선택
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
Labels: feature

#14 메시지 핸들러가 channelRead0를 직접 override 하지 않도록 수정
  src/main/java/databute/databutee/network/message/MessageHandler.java
Labels: bug

#15 서버에 접속하면 등록 요청 전송
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSession.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
  src/main/java/databute/databutee/network/register/RegisterMessage.java
  src/main/java/databute/databutee/network/register/RegisterMessageSerializer.java
Labels: feature

#17 서버에서 수신한 노드 변경 정보에 맞춰 노드 그룹 동기화
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSession.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
  src/main/java/databute/databutee/network/message/MessageHandler.java
  src/main/java/databute/databutee/node/DatabuterNode.java
  src/main/java/databute/databutee/node/DatabuterNodeGroup.java
  src/main/java/databute/databutee/node/add/AddClusterNodeMessage.java
  src/main/java/databute/databutee/node/add/AddClusterNodeMessageDeserializer.java
  src/main/java/databute/databutee/node/add/AddClusterNodeMessageHandler.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessage.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessageDeserializer.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessageHandler.java
Labels: feature

#19 서버에서 수신한 버킷 변경 정보에 맞춰 버킷 그룹 모니터링
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/bucket/Bucket.java
  src/main/java/databute/databutee/bucket/BucketGroup.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessage.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageDeserializer.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageHandler.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationType.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
Labels: feature

#25 버킷 변경 메시지에 factor 정보 추가
  src/main/java/databute/databutee/bucket/Bucket.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessage.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageDeserializer.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageHandler.java
Labels: feature

#27 클러스터 변경 정보를 한 메시지로 통합
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
  src/main/java/databute/databutee/node/DatabuterNodeGroup.java
  src/main/java/databute/databutee/node/add/AddClusterNodeMessageHandler.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessage.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessageDeserializer.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessageHandler.java
  src/main/java/databute/databutee/node/notification/NodeNotificationType.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessage.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessageDeserializer.java
  src/main/java/databute/databutee/node/remove/RemoveClusterNodeMessageHandler.java
Labels: feature

#29 엔티티 모델 구현
  src/main/java/databute/databutee/entity/EmptyEntityKeyException.java
  src/main/java/databute/databutee/entity/Entity.java
  src/main/java/databute/databutee/entity/EntityKey.java
Labels: feature

#31 클러스터 노드가 추가될 때 마다 해당 클러스터에 연결
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/node/DatabuterNode.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessageHandler.java
Labels: feature

#33 버킷과 Databuter 노드 연결
  src/main/java/databute/databutee/bucket/Bucket.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageHandler.java
  src/main/java/databute/databutee/node/DatabuterNodeGroup.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessageHandler.java
Labels: feature

#34 서버와 엔티티 연산 GET, SET, UPDATE, DELETE 프로토콜 구현
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/bucket/BucketGroup.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/entity/EntityMessage.java
  src/main/java/databute/databutee/entity/EntityValueType.java
  src/main/java/databute/databutee/entity/UnsupportedValueTypeException.java
  src/main/java/databute/databutee/entity/delete/DeleteEntityMessage.java
  src/main/java/databute/databutee/entity/delete/DeleteEntityMessageSerializer.java
  src/main/java/databute/databutee/entity/get/GetEntityMessage.java
  src/main/java/databute/databutee/entity/get/GetEntityMessageSerializer.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationErrorCode.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationFailMessage.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationFailMessageDeserializer.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationFailMessageHandler.java
  src/main/java/databute/databutee/entity/result/success/EntityOperationSuccessMessage.java
  src/main/java/databute/databutee/entity/result/success/EntityOperationSuccessMessageDeserializer.java
  src/main/java/databute/databutee/entity/result/success/EntityOperationSuccessMessageHandler.java
  src/main/java/databute/databutee/entity/set/SetEntityMessage.java
  src/main/java/databute/databutee/entity/set/SetEntityMessageSerializer.java
  src/main/java/databute/databutee/entity/update/UpdateEntityMessage.java
  src/main/java/databute/databutee/entity/update/UpdateEntityMessageSerializer.java
  src/main/java/databute/databutee/network/DatabuterChannelHandler.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
  src/main/java/databute/databutee/node/notification/NodeNotificationMessageHandler.java
Labels: feature

#36 비동기적인 네트워크 요청 및 응답 모델 구현
  src/main/java/databute/databutee/Callback.java
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/Dispatcher.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/entity/NotFoundException.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationFailMessageHandler.java
  src/main/java/databute/databutee/entity/result/success/EntityOperationSuccessMessageHandler.java
Labels: feature

#38 엔티티 연산에서 발생하는 에러 코드 추가
  src/main/java/databute/databutee/entity/DuplicateEntityKeyException.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationErrorCode.java
  src/main/java/databute/databutee/entity/result/fail/EntityOperationFailMessageHandler.java
Labels: feature

#39 bucket의 Factor를 keyFactor로 rename
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/bucket/Bucket.java
  src/main/java/databute/databutee/bucket/BucketGroup.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessage.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageDeserializer.java
  src/main/java/databute/databutee/bucket/notification/BucketNotificationMessageHandler.java
Labels: feature

#40 Collection 타입 엔티티 연산 구현
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/entity/EntityValueType.java
  src/main/java/databute/databutee/entity/result/success/EntityOperationSuccessMessageDeserializer.java
  src/main/java/databute/databutee/entity/set/SetEntityMessage.java
  src/main/java/databute/databutee/entity/set/SetEntityMessageSerializer.java
  src/main/java/databute/databutee/entity/update/UpdateEntityMessage.java
  src/main/java/databute/databutee/entity/update/UpdateEntityMessageSerializer.java
Labels: feature

#42 엔트리에 TTL (Time To Live) 구현
  src/main/java/databute/databutee/Databutee.java
  src/main/java/databute/databutee/console/Console.java
  src/main/java/databute/databutee/entity/expire/ExpireEntityMessage.java
  src/main/java/databute/databutee/entity/expire/ExpireEntityMessageSerializer.java
  src/main/java/databute/databutee/network/DatabuterSessionConnector.java
  src/main/java/databute/databutee/network/message/MessageCode.java
Labels: feature
